### ISSUE TITLE
为什么webview弹出层不是弹出来而是位于sketch工作区右侧

### ISSUE THREAD

**Issue by Nealyang** [HelKyle/sketch-scss-plugin#1]
![image](https://user-images.githubusercontent.com/9313216/33753805-33fd92b6-dc24-11e7-986b-5c59646c88e3.png)
如图webView是作为一个弹出层的。为什么博主的在右侧。最近公司需要开发sketch插件，也是在研究插件开发

**Comment by HelKyle** [comment]
看代码怎么写的了，NSPanel 创建出来就是一个弹出层

**Comment by Nealyang** [comment]
`    var windowObject = webView.windowScriptObject();
    var delegate = new MochaJSDelegate({
        "webView:didChangeLocationWithinPageForFrame:": (function (webView, webFrame) {
            var locationHash = windowObject.evaluateWebScript("window.location.hash");
            var hash = parseHash(locationHash);
        }),
        "webView:didFinishLoadForFrame:": (function (webView, webFrame) {
            getAllTextLayer(context);
        })
    });

    webView.setFrameLoadDelegate_(delegate.getClassInstance());`

通过设置MochaJSDelegate可以知道webView中资源是否加载完毕，当我把弹出层的那种加载webView的方式实现后，这样是没有问题的，但是当我采用博主的方式去实现的时候，这段代码是不能加上的，会倒是闪退。

请问采用博主的这种加载webView的方式，如何知道webView中页面的js资源都加载完毕了呢

项目地址：[sketch Plugin](https://github.com/Nealyang/TextGrid-Rename-Sketch-plugin)

**Comment by Nealyang** [comment]
因为需要在初始化的时候，就运行js中的某一个方法，也就是上面的getAllTextLayer这个方法，但是在已加载完就去执行这个方法，是没有任何效果的，估计是因为js还没有下载完成

**Comment by HelKyle** [comment]
@Nealyang webView 是否加载完完成是通过 delegate 去触发的，CocoaScript 执行 webview js 代码是通过 windowObject.evaluateWebScript 执行的，并不能直接调用 webview 里面的 js 代码

**Comment by Nealyang** [comment]
是的，但是现在的问题就是通过NSPanel，可以在"webView:didFinishLoadForFrame:"监听中去调用webView的js代码，但是通过博主的这种方式，首先webView不能够setFrameLoadDelegate_，否则直接闪退。不能够使用MochaJSDelegate，我就不知道如何判断webView中js代码是否加载完全，不然通过windowObject.evaluateWebScript执行不到js中的代码。请问博主这个有什么好的解决方法不

**Comment by HelKyle** [comment]
https://awkward.co/blog/how-to-create-floating-sketch-plugins-ii/ 这篇文章或许能帮到你

**Comment by Nealyang** [comment]
非常感谢~其实我就是参考的这篇文章写得插件

`// Set the delegate on the WebView
webView.setFrameLoadDelegate_(delegate.getClassInstance());`

这行代码在NSPanel弹出层的那种实现方式中，这样没问题，但是如果设置成窗口的一部分，就像博主的实现方式，这句代码会引起闪退

再次感谢博主回复，我再查一查
